# Generated by Django 5.0.7 on 2024-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tags',
            field=models.ManyToManyField(related_name='news', to='api.tag'),
        ),
    ]
